pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Vaultscan') {
            steps {
                sh 'java -jar target/vaultscan-1.0-SNAPSHOT.jar scan . --format junit --output target/vaultscan-junit.xml --fail-on high'
            }
            post {
                always {
                    junit 'target/vaultscan-junit.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
